name: camerapi
description: Flutter-Pi plugin for displaying the camera stream and scanning QR/Barcodes.
# repository: https://github.com/flutter/plugins/tree/main/packages/video_player/video_player
# issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+video_player%22
version: 1.0.0

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.0
  camerapi_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  camerapi_platform_interface:
    path: ../camerapi_platform_interface
